[package]
name = "popparoach"
version = "0.1.2"
authors = ["iriri"]
edition = "2021"

repository = "https://github.com/iriri/popparoach"
license = "BSD-3-Clause"
description = "Cut my life into pieces"

[features]
nightly = []
